name: RazasX
description: Plugin para gestionar Razas en el servidor de Minecraft.
author: Ewahv1
main: me.ewahv1.plugin.Main
version: 0.0.1
api-version: 1.20
commands:
  Razas:
    description: Abre el inventario para seleccionar una raza.
    usage: /Razas